# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GRVS Code 
email: 
description: > # this means to ignore newlines until "baseurl:"
  General Relativistic Vorticity Solver - code used to solve for the geodesic of a particle in a general spacetime and computing the resulting magnetic field seed.
baseurl: "/grvs" # the subpath of your site, e.g. /blog
url: "http://rogeriodejesusjorge.github.io/GRVS" # the base hostname & protocol for your site
twitter_username: shufflingroger
github_username:  rogeriodejesusjorge

# Build settings
markdown: kramdown
